Repository buildo/mailo, pull requests merged in 2018-07, with the labels that each got.

#52 #51: Add git-crypt (closes #51)
  .drone.sec
  .drone.yml
  .git-crypt/.gitattributes
  .git-crypt/keys/default/0/3AC6A7506F4ACFCD7D8704BF2965749C34FB5468.gpg
  .git-crypt/keys/default/0/EBA56C16E8DD735E752E5B4F1A9DB6FF48BD0BBC.gpg
  .gitattributes
  .gitignore
  secrets.yml
  src/test/resources/application.conf.cast5
Labels: WIP

#50 #49: Add scalafmt (closes #49)
  .gitignore
  .scalafmt.conf
  src/main/scala/mailo/TemplateParser.scala
  src/main/scala/mailo/data/S3MailData.scala
  src/main/scala/mailo/http/MailClient.scala
  src/main/scala/mailo/http/MailgunClient.scala
  src/main/scala/mailo/package.scala
Labels: WIP

#54 #53: Improve mailo style (closes #53)
  .gitattributes
  src/main/scala/mailo/data/S3MailData.scala
  src/main/scala/mailo/data/S3MailDataError.scala
  src/main/scala/mailo/http/MailClient.scala
  src/main/scala/mailo/models.scala
  src/main/scala/mailo/package.scala
  src/main/scala/mailo/parser/ParserError.scala
  src/main/scala/mailo/parser/TemplateParser.scala
Labels: waiting for merge

#55 add Sendinblue support
  build.sbt
  src/main/scala/mailo/http/SendinblueClient.scala
  src/main/scala/mailo/package.scala
  src/test/resources/application.conf.cast5
  src/test/scala/mailo/CacheSpec.scala
  src/test/scala/mailo/MailoSpec.scala
  src/test/scala/mailo/PDF.scala
  src/test/scala/mailo/SendinblueSpec.scala
Labels: in review

#58 #57: Early release (closes #57)
  .drone.sec
  .drone.yml
  build.sbt
  project/plugins.sbt
  secrets.yml
Labels: waiting for merge
