Repository buildo/mailo, pull requests merged in 2019-03, with the labels that each got.

#73 fixed attachment java code following SiB api behavior change
  src/main/scala/mailo/http/MailClient.scala
  src/main/scala/mailo/http/MailgunClient.scala
  src/main/scala/mailo/http/SendinblueClient.scala
  src/test/scala/mailo/SendinblueSpec.scala
Labels: in review

#75 #74: SMTP client (closes #74)
  .drone.yml
  .gitignore
  build.sbt
  project/build.properties
  src/main/scala/mailo/http/SMTPClient.scala
  src/test/resources/reference.conf
  src/test/scala/mailo/MailoSMTPSpec.scala
Labels: WIP

#77 #76: MailData: FS implementation (closes #76)
  src/main/scala/mailo/data/FSMailData.scala
  src/test/scala/mailo/FSMailDataSpec.scala
Labels: waiting for merge
